"use client";

import NextLink from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { AIRequest } from "../data/mock-data";
import { UsageRecord } from "../lib/usage-record";
import { dailySpend, rangeStart } from "../lib/spend-range";
import { useDemo } from "./demo-context";

type Page = "overview" | "requests" | "request-detail" | "analytics" | "settings";
type Range = 7 | 30 | 90 | 365;

const icons = { grid: "⊞", requests: "≡", analytics: "◔", settings: "⚙", search: "⌕", chevron: "⌄", export: "⇩", arrow: "↗", dots: "•••", back: "←", external: "↗", copy: "⧉" };
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2, maximumFractionDigits: 4 });

function Icon({ name }: { name: keyof typeof icons }) { return <span className="icon" aria-hidden="true">{icons[name]}</span>; }
function formatCost(value: number) { return money.format(value); }
function compactNumber(value: number) { return new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 }).format(value); }
function ProviderMark({ provider }: { provider: string }) { const letter = provider === "OpenAI" ? "O" : provider === "Anthropic" ? "A" : "G"; return <span className={`provider-mark ${provider.toLowerCase()}`}>{letter}</span>; }

type LedgerRequest = AIRequest & { recordedAt: string; metadata?: Record<string, string | number | boolean> };

function displayTime(timestamp: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(timestamp)); }
function fromUsage(record: UsageRecord): LedgerRequest {
  return { id: record.id, timestamp: displayTime(record.timestamp), recordedAt: record.timestamp, provider: record.provider, model: record.model, feature: record.attribution.feature ?? "Unattributed", customer: record.attribution.customer ?? "Unattributed", inputTokens: record.inputTokens, outputTokens: record.outputTokens, latency: `${(record.latencyMs / 1000).toFixed(2)}s`, cost: record.cost ?? 0, status: record.status === "success" ? "Success" : "Failed", metadata: record.attribution.metadata };
}
function Link({ href, ...props }: React.ComponentProps<typeof NextLink>) {
  const demo = useDemo();
  const target = demo && typeof href === "string" && href.startsWith("/") ? `/workspace${href === "/" ? "" : href}` : href;
  return <NextLink {...props} href={target} />;
}

function ExportButton({ compact = false }: { compact?: boolean }) {
  const demo = useDemo();
  if (!demo) return <a className="button button-secondary" href="/api/usage/export" download><Icon name="export" />{compact ? "Export" : "Export CSV"}</a>;
  function download() {
    if (!demo) return;
    const quote = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;
    const rows = demo.records.map((r) => [r.id, r.timestamp, r.provider, r.model, r.attribution.feature, r.attribution.customer, r.inputTokens, r.outputTokens, r.totalTokens, r.latencyMs, r.cost, r.status].map(quote).join(","));
    const url = URL.createObjectURL(new Blob([["id,timestamp,provider,model,feature,customer,input_tokens,output_tokens,total_tokens,latency_ms,cost_usd,status", ...rows].join("\n")], { type: "text/csv;charset=utf-8" }));
    const link = document.createElement("a"); link.href = url; link.download = "costlens-usage.csv"; link.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <button className="button button-secondary" onClick={download}><Icon name="export" />{compact ? "Export" : "Export CSV"}</button>;
}

function useLedger() {
  const demo = useDemo();
  const isDemo = Boolean(demo);
  const [records, setRecords] = useState<LedgerRequest[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    if (isDemo) return;
    const controller = new AbortController();
    fetch("/api/usage?limit=10000", { signal: controller.signal })
      .then((response) => response.ok ? response.json() : Promise.reject())
      .then((data: { records?: UsageRecord[] }) => setRecords((data.records ?? []).map(fromUsage)))
      .catch(() => { if (!controller.signal.aborted) setRecords([]); })
      .finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [isDemo]);
  return { records: demo ? demo.records.map(fromUsage) : records, loading: demo ? false : loading };
}

function Shell({ page, children }: { page: Page; children: React.ReactNode }) {
  const demo = useDemo();
  const isDemo = Boolean(demo);
  const nav = [["overview", "Overview", "/", "grid"], ["requests", "Requests", "/requests", "requests"], ["analytics", "Analytics", "/analytics", "analytics"]] as const;
  const [liveWorkspace, setWorkspace] = useState({ ownerName: "", organizationName: "CostLens" });
  useEffect(() => { if (isDemo) return; fetch("/api/setup").then((response) => response.json()).then((data: { profile?: { ownerName: string; organizationName: string } }) => { if (data.profile) setWorkspace(data.profile); }).catch(() => undefined); }, [isDemo]);
  const workspace = demo ? { ownerName: demo.email, organizationName: "Arcade Labs" } : liveWorkspace;
  const initials = workspace.ownerName.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase() || "CL";
  return <div className="app-shell"><aside className="sidebar"><Link className="brand" href="/"><span className="brand-mark">◒</span><span>CostLens</span></Link><div className="workspace"><span className="workspace-mark">{workspace.organizationName[0]?.toUpperCase() ?? "C"}</span><span>{workspace.organizationName}</span><Icon name="chevron" /></div><nav className="nav" aria-label="Main navigation">{nav.map(([id, label, href, icon]) => <Link className={`nav-link ${page === id || (page === "request-detail" && id === "requests") ? "active" : ""}`} href={href} key={id}><Icon name={icon} />{label}</Link>)}</nav><div className="sidebar-footer">{demo ? <><Link className={`nav-link ${page === "settings" ? "active" : ""}`} href="/settings"><Icon name="settings" />Settings</Link><button className="nav-link demo-exit" onClick={demo.exit}>← Sign out</button></> : <><NextLink className="nav-link" href="/workspace">↗ Open workspace</NextLink><Link className={`nav-link ${page === "settings" ? "active" : ""}`} href="/settings"><Icon name="settings" />Settings</Link></>}<div className="profile"><span className="avatar">{initials}</span><span className="profile-copy"><b>{workspace.ownerName || "CostLens user"}</b><small>{workspace.organizationName}</small></span><Icon name="dots" /></div></div></aside><main className="main"><div className="workspace-topbar"><span>COSTLENS <span className="topbar-slash">/</span> {workspace.organizationName}</span><div className="workspace-topbar-actions">{demo && <><span className="sync-state" role="status">{demo.refreshing ? "Syncing activity" : `Updated ${new Date(demo.generatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}`}</span><button className="button button-secondary refresh-button" onClick={demo.refresh} disabled={demo.refreshing}><span className={demo.refreshing ? "demo-spinning" : ""}>↻</span>{demo.refreshing ? "Refreshing" : "Refresh"}</button><button className="mobile-signout" onClick={demo.exit}>Sign out</button></>}<span className="workspace-region">USD</span></div></div><nav className="mobile-nav" aria-label="Workspace navigation">{nav.map(([id, label, href]) => <Link key={id} href={href} className={page === id ? "active" : ""}>{label}</Link>)}<Link href="/settings">Settings</Link></nav>{children}</main></div>;
}

function PageTop({ title, eyebrow }: { title: string; eyebrow?: string }) { return <header className="page-top"><div><p className="eyebrow">{eyebrow ?? "Usage & costs"}</p><h1>{title}</h1></div><div className="top-actions"><ExportButton /><a className="button button-primary" href="https://openrouter.ai/docs" target="_blank" rel="noreferrer">OpenRouter docs <Icon name="arrow" /></a></div></header>; }

function RangeControl({ range, onChange }: { range: Range; onChange: (range: Range) => void }) { return <div className="toolbar"><div className="segmented">{([7, 30, 90, 365] as Range[]).map((value) => <button className={range === value ? "selected" : ""} onClick={() => onChange(value)} key={value}>{value === 365 ? "12M" : `${value}D`}</button>)}</div><span className="date-button">Last {range === 365 ? "12 months" : `${range} days`}</span></div>; }
function withinRange(records: LedgerRequest[], range: Range) { const now = new Date(); const cutoff = rangeStart(range, now); return records.filter((record) => { const time = new Date(record.recordedAt).getTime(); return time >= cutoff && time <= now.getTime(); }); }

function EmptyState({ title, detail, action }: { title: string; detail: string; action?: React.ReactNode }) { return <div className="empty-state"><strong>{title}</strong><p>{detail}</p>{action}</div>; }

function MetricCard({ label, value, note, icon }: { label: string; value: string; note: string; icon: string }) { return <section className="metric-card"><div className="metric-top"><span>{label}</span><span className="metric-icon">{icon}</span></div><strong>{value}</strong><p><span>{note}</span></p></section>; }

type BreakdownRow = { label: string; value: number; color?: string };
function Breakdown({ title, subtitle, rows, href }: { title: string; subtitle: string; rows: BreakdownRow[]; href: string }) { const max = Math.max(...rows.map((row) => row.value), 1); return <section className="panel breakdown"><div className="panel-heading"><div><h2>{title}</h2><p>{subtitle}</p></div><Link className="text-button" href={href}>Explore <Icon name="arrow" /></Link></div>{rows.length ? <div className="breakdown-rows">{rows.slice(0, 5).map((row, index) => <div className="breakdown-row" key={row.label}><span className="provider-color" style={{ background: row.color ?? ["#ffffff", "#b8b8bf", "#88888f", "#606067"][index % 4] }} /><div className="breakdown-label"><b>{row.label}</b><div className="progress-track"><i className="progress" style={{ width: `${(row.value / max) * 100}%` }} /></div></div><div className="breakdown-value"><b>{formatCost(row.value)}</b><small>{max ? `${((row.value / rows.reduce((sum, item) => sum + item.value, 0)) * 100).toFixed(1)}%` : "0%"}</small></div></div>)}</div> : <EmptyState title="No cost data yet" detail="Tracked requests will appear here." />}</section>; }

function SpendChart({ records, range }: { records: LedgerRequest[]; range: Range }) { const days = dailySpend(records, range); const max = Math.max(...days.map((day) => day.value), 1); const points = days.map((day, index) => `${(index / (range - 1)) * 100},${88 - (day.value / max) * 65}`).join(" "); const area = `0,100 ${points} 100,100`; return <section className="panel chart-panel"><div className="panel-heading"><div><h2>Spend over time</h2><p>Daily AI cost across tracked requests</p></div><span className="ghost-button">Daily</span></div>{records.length ? <><div className="chart-legend"><span className="legend-dot" /> Total spend <b>{formatCost(records.reduce((sum, record) => sum + record.cost, 0))}</b></div><div className="line-chart"><div className="chart-scale"><span>{formatCost(max)}</span><span>{formatCost(max / 2)}</span><span>$0</span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={`AI spend over the last ${range} days (UTC)`}><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#ffffff" stopOpacity=".24" /><stop offset="100%" stopColor="#ffffff" stopOpacity="0" /></linearGradient></defs><polygon points={area} fill="url(#fill)" /><polyline points={points} fill="none" stroke="#ffffff" strokeWidth="1.4" vectorEffect="non-scaling-stroke" /></svg><div className="chart-labels"><span>{days[0].key}</span><span>Today (UTC)</span></div></div></> : <EmptyState title="No spend to chart" detail="Send a request through CostLens to start tracking daily spend." />}</section>; }

function RequestTable({ records, loading }: { records: LedgerRequest[]; loading: boolean }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [model, setModel] = useState("all"); const [feature, setFeature] = useState("all"); const [customer, setCustomer] = useState("all"); const [page, setPage] = useState(0); const pageSize = 12;
  const choices = (key: "model" | "feature" | "customer") => Array.from(new Set(records.map((record) => record[key])));
  const filtered = records.filter((record) => `${record.model} ${record.provider} ${record.feature} ${record.customer}`.toLowerCase().includes(query.toLowerCase()) && (status === "all" || record.status === status) && (model === "all" || record.model === model) && (feature === "all" || record.feature === feature) && (customer === "all" || record.customer === customer));
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const filterKey = `${query}|${status}|${model}|${feature}|${customer}`;
  const [previousFilterKey, setPreviousFilterKey] = useState(filterKey);
  if (filterKey !== previousFilterKey) { setPreviousFilterKey(filterKey); setPage(0); }
  const visible = filtered.slice(page * pageSize, (page + 1) * pageSize);
  return <section className="panel requests-panel"><div className="panel-heading table-heading"><div><h2>Request history</h2><p>Every recorded AI request, token count, and dollar.</p></div><div className="table-controls"><label className="search"><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search requests" /></label><ExportButton compact /></div></div><div className="filters"><select className="filter-pill selected" aria-label="Filter by status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All requests</option><option value="Success">Success</option><option value="Failed">Failed</option></select><select className="filter-pill" aria-label="Filter by model" value={model} onChange={(event) => setModel(event.target.value)}><option value="all">All models</option>{choices("model").map((item) => <option key={item}>{item}</option>)}</select><select className="filter-pill" aria-label="Filter by feature" value={feature} onChange={(event) => setFeature(event.target.value)}><option value="all">All features</option>{choices("feature").map((item) => <option key={item}>{item}</option>)}</select><select className="filter-pill" aria-label="Filter by customer" value={customer} onChange={(event) => setCustomer(event.target.value)}><option value="all">All customers</option>{choices("customer").map((item) => <option key={item}>{item}</option>)}</select></div>{loading ? <EmptyState title="Loading ledger" detail="Fetching your recorded usage." /> : visible.length ? <div className="table-wrap"><table><thead><tr><th>Timestamp</th><th>Model</th><th>Feature</th><th>Customer</th><th>Tokens</th><th>Latency</th><th>Cost</th><th>Status</th></tr></thead><tbody>{visible.map((request) => <tr key={request.id}><td><Link className="request-time" href={`/requests/${request.id}`}>{request.timestamp}<small>{request.id}</small></Link></td><td><span className="model-cell"><ProviderMark provider={request.provider} />{request.model}</span></td><td>{request.feature}</td><td>{request.customer}</td><td>{(request.inputTokens + request.outputTokens).toLocaleString()}</td><td>{request.latency}</td><td className="cost-cell">{formatCost(request.cost)}</td><td><span className={`status ${request.status === "Success" ? "success" : "warning"}`}><i />{request.status}</span></td></tr>)}</tbody></table></div> : <EmptyState title="No matching requests" detail="Track a request through CostLens, or adjust the current filters." /> }<footer className="table-footer"><span>Showing {visible.length} of {filtered.length} requests</span><div><button className="page-button" disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</button><button className="page-button" disabled={page + 1 >= totalPages} onClick={() => setPage(page + 1)}>Next</button></div></footer></section>;
}

function Overview() { const { records, loading } = useLedger(); const [range, setRange] = useState<Range>(30); const scoped = withinRange(records, range); const total = scoped.reduce((sum, record) => sum + record.cost, 0); const group = (key: "provider" | "model" | "feature" | "customer") => Object.entries(scoped.reduce<Record<string, number>>((accumulator, record) => ({ ...accumulator, [record[key]]: (accumulator[record[key]] ?? 0) + record.cost }), {})).map(([label, value]) => ({ label, value })).sort((a, b) => b.value - a.value); return <Shell page="overview"><PageTop title="Overview" /><RangeControl range={range} onChange={setRange} /><div className="metrics"><MetricCard label="Total AI spend" value={formatCost(total)} note={`Last ${range === 365 ? "12 months" : `${range} days`}`} icon="◒" /><MetricCard label="Total requests" value={scoped.length.toLocaleString()} note="Tracked requests" icon="↗" /><MetricCard label="Total tokens" value={compactNumber(scoped.reduce((sum, record) => sum + record.inputTokens + record.outputTokens, 0))} note="Input + output tokens" icon="◇" /><MetricCard label="Avg. cost per request" value={formatCost(scoped.length ? total / scoped.length : 0)} note="Across selected period" icon="◌" /></div><SpendChart records={scoped} range={range} /><div className="two-column"><Breakdown title="Cost by model" subtitle="Your highest-cost models" rows={group("model")} href="/analytics" /><Breakdown title="Cost by provider" subtitle="Spend across providers" rows={group("provider")} href="/analytics" /></div><div className="two-column"><Breakdown title="Cost by feature" subtitle="Features driving AI spend" rows={group("feature")} href="/analytics" /><Breakdown title="Cost by customer" subtitle="Customer-level allocation" rows={group("customer")} href="/analytics" /></div>{loading ? <EmptyState title="Loading ledger" detail="Fetching your recorded usage." /> : <RequestTable records={scoped.slice(0, 6)} loading={false} />}</Shell>; }
function Requests() { const ledger = useLedger(); return <Shell page="requests"><PageTop title="Requests" eyebrow="AI request ledger" /><RequestTable records={ledger.records} loading={ledger.loading} /></Shell>; }
function Analytics() { const { records, loading } = useLedger(); const [range, setRange] = useState<Range>(30); const scoped = withinRange(records, range); const group = (key: "provider" | "model" | "feature" | "customer") => Object.entries(scoped.reduce<Record<string, number>>((accumulator, record) => ({ ...accumulator, [record[key]]: (accumulator[record[key]] ?? 0) + record.cost }), {})).map(([label, value]) => ({ label, value })).sort((a, b) => b.value - a.value); return <Shell page="analytics"><PageTop title="Analytics" eyebrow="Cost intelligence" /><RangeControl range={range} onChange={setRange} />{loading ? <EmptyState title="Loading analytics" detail="Fetching your recorded usage." /> : <><section className="analytics-hero panel"><div><span className="eyebrow">SELECTED PERIOD</span><h2>{formatCost(scoped.reduce((sum, record) => sum + record.cost, 0))} in tracked AI spend.</h2><p>Explore cost drivers by model, provider, feature, and customer.</p></div><Link className="button button-primary" href="/requests">Explore requests <Icon name="arrow" /></Link></section><div className="two-column"><Breakdown title="Model comparison" subtitle="Spend by model" rows={group("model")} href="/requests" /><Breakdown title="Provider comparison" subtitle="Spend by provider" rows={group("provider")} href="/requests" /></div><SpendChart records={scoped} range={range} /><div className="two-column"><Breakdown title="Feature comparison" subtitle="Features generating the highest costs" rows={group("feature")} href="/requests" /><Breakdown title="Customer comparison" subtitle="Customer-level cost allocation" rows={group("customer")} href="/requests" /></div></>}</Shell>; }
function Detail({ requestId }: { requestId?: string }) { const params = useParams<{ id: string }>(); const id = requestId ?? params.id; const { records, loading } = useLedger(); const request = records.find((record) => record.id === id); const [copied, setCopied] = useState(false); if (loading) return <Shell page="request-detail"><EmptyState title="Loading request" detail="Fetching the requested ledger entry." /></Shell>; if (!request) return <Shell page="request-detail"><EmptyState title="Request not found" detail="This record is not in the current workspace." action={<Link className="button button-primary" href="/requests">Back to requests</Link>} /></Shell>; const totalTokens = request.inputTokens + request.outputTokens; const copyId = async () => { await navigator.clipboard.writeText(request.id); setCopied(true); setTimeout(() => setCopied(false), 1800); }; return <Shell page="request-detail"><div className="detail-back"><Link href="/requests"><Icon name="back" /> All requests</Link></div><header className="detail-header"><div><p className="eyebrow">REQUEST DETAILS</p><h1>{request.id}</h1><p>{request.timestamp} · <span className={`status ${request.status === "Success" ? "success" : "warning"}`}><i />{request.status}</span></p></div><div className="top-actions"><button className="button button-secondary" onClick={copyId}><Icon name="copy" />{copied ? "Copied" : "Copy ID"}</button></div></header><div className="detail-grid"><section className="panel cost-hero"><p>Total request cost</p><strong>{formatCost(request.cost)}</strong><div><span><b>{totalTokens.toLocaleString()}</b> total tokens</span><span><b>{request.latency}</b> latency</span></div></section><section className="panel detail-summary"><h2>Request summary</h2><dl><div><dt>Provider</dt><dd><ProviderMark provider={request.provider} /> {request.provider}</dd></div><div><dt>Model</dt><dd>{request.model}</dd></div><div><dt>Feature</dt><dd>{request.feature}</dd></div><div><dt>Customer</dt><dd>{request.customer}</dd></div></dl></section></div><div className="detail-grid lower"><section className="panel token-panel"><div className="panel-heading"><div><h2>Token usage</h2><p>Input and output token breakdown</p></div></div><div className="token-total"><strong>{totalTokens.toLocaleString()}</strong><span>Total tokens</span></div><div className="token-bars"><div><span>Input</span><i><b style={{ width: `${(request.inputTokens / (totalTokens || 1)) * 100}%` }} /></i><strong>{request.inputTokens.toLocaleString()}</strong></div><div><span>Output</span><i><b className="output" style={{ width: `${(request.outputTokens / (totalTokens || 1)) * 100}%` }} /></i><strong>{request.outputTokens.toLocaleString()}</strong></div></div></section><section className="panel metadata"><div className="panel-heading"><div><h2>Metadata</h2><p>Custom attributes attached to this request</p></div></div><pre>{JSON.stringify(request.metadata ?? {}, null, 2)}</pre></section></div></Shell>; }
function Settings() {
  const demo = useDemo();
  const isDemo = Boolean(demo);
  const [configured, setConfigured] = useState(false);
  const [profile, setProfile] = useState<{ ownerName: string; organizationName: string } | null>(null);
  useEffect(() => {
    if (isDemo) return;
    fetch("/api/openrouter/status").then((response) => response.json()).then((data: { configured?: boolean }) => setConfigured(Boolean(data.configured))).catch(() => setConfigured(false));
    fetch("/api/setup").then((response) => response.json()).then((data: { profile?: { ownerName: string; organizationName: string } }) => setProfile(data.profile ?? null)).catch(() => undefined);
  }, [isDemo]);
  if (demo) return <Shell page="settings"><PageTop title="Settings" eyebrow="Workspace preferences" /><div className="settings-layout"><section className="panel settings-panel"><div className="panel-heading"><div><h2>Workspace</h2><p>Your account and workspace preferences.</p></div></div><dl className="about-list"><div><dt>Organization</dt><dd>Arcade Labs</dd></div><div><dt>Account</dt><dd>{demo.email}</dd></div><div><dt>Currency</dt><dd>USD</dd></div><div><dt>Region</dt><dd>US East</dd></div></dl></section><section className="panel settings-panel"><div className="panel-heading"><div><h2>Activity</h2><p>Request history and cost attribution.</p></div></div><div className="connection"><span className="connection-dot" /><div><b>Workspace session active</b><p>Activity updates automatically while your workspace is open.</p></div><button className="button button-secondary" disabled={demo.refreshing} onClick={demo.refresh}>{demo.refreshing ? "Refreshing" : "Refresh"}</button></div></section><section className="panel settings-panel"><div className="panel-heading"><div><h2>Session</h2><p>Signed in as {demo.email}</p></div><button className="button button-secondary" onClick={demo.exit}>Sign out</button></div></section></div></Shell>;
  return <Shell page="settings"><PageTop title="Settings" eyebrow="Workspace preferences" /><div className="settings-layout"><section className="panel settings-panel"><div className="panel-heading"><div><h2>Workspace</h2><p>Owner and organization for this installation.</p></div><Link className="text-button" href="/setup">Edit <Icon name="arrow" /></Link></div><dl className="about-list"><div><dt>Owner</dt><dd>{profile?.ownerName || "Not set"}</dd></div><div><dt>Organization</dt><dd>{profile?.organizationName || "Not set"}</dd></div><div><dt>Cost currency</dt><dd>USD — reported by OpenRouter</dd></div></dl></section><section className="panel settings-panel"><div className="panel-heading"><div><h2>Data source</h2><p>Manage your workspaces and provider connection.</p></div></div><div className="connection"><span className="connection-dot off" /><div><b>Workspace access</b><p>Open your cost intelligence workspace.</p></div><NextLink className="button button-secondary" href="/workspace">Open workspace</NextLink></div><div className="connection"><span className={`connection-dot ${configured ? "" : "off"}`} /><div><b>OpenRouter</b><p>{configured ? "Configured and ready to record live requests." : "Add your OpenRouter API key to start recording live requests."}</p></div><Link className={`button ${configured ? "button-secondary" : "button-primary"}`} href="/setup">{configured ? "Manage key" : "Add API key"}</Link></div></section><section className="panel settings-panel"><div className="panel-heading"><div><h2>About CostLens</h2><p>Open-source AI cost intelligence</p></div></div><dl className="about-list"><div><dt>Version</dt><dd>0.1.0</dd></div><div><dt>License</dt><dd>MIT</dd></div></dl></section></div></Shell>;
}
export function CostLensApp({ page, requestId }: { page: Page; requestId?: string }) { if (page === "requests") return <Requests />; if (page === "request-detail") return <Detail requestId={requestId} />; if (page === "analytics") return <Analytics />; if (page === "settings") return <Settings />; return <Overview />; }
